name: Examples
filename: lsd.js
description: Some examples of what LSD can do. Turn your brain into shit.
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
authors: Yaroslaff Fedin
sources:
  - Source/Application/Application.js
  - Source/Application/Network.js
  - Source/Application/Preferences.js
  - Source/Application/Browser.js
  - Source/Application/Desktop.js